name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages !
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci

      - name: Lint and format
        run: |
            npm run lint
            npm run format
        env:
          VITE_APP_NAME: App
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5

  test:
    name: Test Unit
    env:
      VITE_APP_NAME: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm run test
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    env:
      VITE_APP_NAME: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: Build prod
        run: npm run build
      - name: Creation artefact
        uses: actions/upload-artifact@v4
        with:
            name: dist
            path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      VITE_APP_NAME: Prod
    steps:
      - name: Recuperer le dossier dist
        uses: actions/download-artifact@v4
        with:
            name: dist

      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
           start: npm run preview
           wait-on: 'http://localhost:3000/'
           browser: chrome

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
